### PR TITLE
Coverage for failing tests

### LINKED ISSUE #57: Coverage for failing tests
Currently if one test is failing the whole pipeline stops and no coverage reports can be created.
In my opinion if a test is failing it should still be possible to generate coverage for the non-failing parts. 

Corresponding merge request is on the way.

### PR DESCRIPTION
**Pull request by briederer**
Adds a safety measure to still process .cov files even when tests are failing.

Closes #57

### CODE REVIEW

**Comment by briederer** [comment]
Sorry for messing with the tests.
I wanted to achieve that the tests for this package are succeeding while in general they generate_coverage still fails.
Therefore it was neccessary to add the `should_throw` argument to `test_coverage` function.
This checks now that the .cov files are processed correctly even if `generate_coverage` still fails when one or more tests are failing.

**Comment by briederer** [comment]
@tpapp Ready for review

File: src/LocalCoverage.jl [hunk 1]
```diff
@@ -233,13 +233,35 @@ function generate_coverage(pkg = nothing;
...
+
+"""
+$(SIGNATURES)
+
+Process coverage files for a package within folder.
+    
+Called by [`generate_coverage`](@ref).
+
+"""
+
```
Comment (tpapp) [inline src/LocalCoverage.jl:261]: remove empty newline
```suggestion
```

File: test/runtests.jl [hunk 2]
```diff
@@ -40,14 +61,6 @@ function test_coverage(pkg;
...
     end
 
-    buffer = IOBuffer()
-    show(buffer, cov)
-    table = String(take!(buffer))
-    println(table)
-    @test !isnothing(match(table_header, table))
-    @test !isnothing(match(table_line, table))
-    @test !isnothing(match(table_footer, table))
-
```
Comment (tpapp) [inline test/runtests.jl:50]: why was this removed?

File: test/runtests.jl [hunk 3]
```diff
@@ -59,10 +72,6 @@ function test_coverage(pkg;
 
     @test isfile(lcovtrace)
     rm(covdir, recursive = true)
-
-    @info "Printing coverage information for visual debugging"
-    show(stdout, cov)
-    show(IOContext(stdout, :print_gaps => true), cov)
```
Comment (tpapp) [inline test/runtests.jl:65]: why was this removed?

**Review by tpapp — COMMENTED** [review]
thanks, but I don't understand why some code was removed, please explain

File: test/runtests.jl (hunk 2 above)
Comment (briederer) [reply test/runtests.jl:50]: It was not removed. It was moved up to line 42 and beyond.
The reason is, that for the new test case of a failing test in the dummy package no coverage is returned, but instead throws an error. Therefore all the tests using `cov` cannot be processed, after the test has thrown.

So there is no change in the tests for the old ones, but an adaption for the test of the new feature.

File: test/runtests.jl (hunk 3 above)
Comment (briederer) [reply test/runtests.jl:65]: Same as before.

**Comment by briederer** [comment]
Thanks for the review. Added a clarification comment to your question

**Comment by briederer** [comment]
Short reminder

**Comment by tpapp** [comment]
Thanks, I appreciate the reminder. The code now looks good to me.

I am wondering if proceeding in case of an error is always desirable. Would an argument that controls this for `generate_coverage` make sense? The new behavior could be the default.

Can you please add a section (eg `# Error handling`) to the documentation of `generate_coverage` that explains the new behavior? Just that errors are caught and coverage is still generated.
